@startuml Bill Generator pipe and filter
title Bill Generator pipe and filter (nivel de compoñente)
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System_Ext(client, "Cliente", "Quere facer uso do sistema")

Boundary(pipeline_system, "Sistema en pipeline"){
    Container(bill_generator, "Bill Generator", "Interface coa que se comunica o usuario"){
        Component(bill_generator1, "Interface", "Recolle os datos proporcionados polo usuario e encamíñaos áo filtro calculadora.")
    }
    Container(bill_calculator, "Bill Calculator", "Filtro encargado de calcular os prezos de cada liña de factura así como o total desta."){
        Component(bill_calculator1, "Calculadora", "Recibe unha lista de liñas de pedido e calcula os totais de cada liña e vai acumulando un total global.")
    }
    Container(latex_formatter, "LaTeX Formatter", "Filtro encargado de formatear e embeber a factura xa calculada en código LaTeX."){
        Component(latex_formatter1, "Formateador das liñas e total da factura", "Encárgase de xerar o código LaTeX dependente das liñas da factura.")
        Component(latex_formatter2, "Formateador da estrutura da factura", "Encárgase de formatear e embeber o comprador, vendedor, e liñas da factura e estructuralizalas no documento.")
    }
    Container(latex_to_pdf, "LaTeX to PDF", "Filtro encargado de compilar o código LaTeX, xerando, e exportando a factura en formato PDF."){
        Component(latex_to_pdf1, "Interface", "Recibe o código LaTeX e calcula o nome do ficheiro en base á data e hora actual.")
        Component(latex_to_pdf2, "Iona (Document generation using LaTeX)", "Dependencia que compila código LaTeX e xera documentos PDF.")
    }
}

Rel(client, bill_generator1, "Envía", "Petición ao Bill Generator.", "Introduce a petición ao pipeline")
Rel(bill_generator1, bill_calculator1, "Envía", "Os datos da factura.", "Introduce a os datos na calculadora para ser computados e procesados.")
Rel(bill_calculator1, latex_formatter1, "Envía", "Os datos da factura e o total global e por liñas xa calculados.", "Introduce os datos ao formateador para xerar o código.")
Rel(latex_formatter1, latex_formatter2, "Envía", "O fragmento de código LaTeX relativo aos productos e prezos calculados.", "Embebe o código das liñas da factura (e total) dentro do código da estrutura completa da factura.")
Rel(latex_formatter2, latex_to_pdf1, "Envía", "O código LaTeX relativo á factura.", "Introduce o código ao filtro compilador para xerar o documento.")
Rel(latex_to_pdf1, latex_to_pdf2, "Envía", "O código LaTeX completo e o nome do ficheiro onde se vai gardar.", "Introduce o código fonte no compilador e o nome do ficheiro.")
Rel(latex_to_pdf2, bill.pdf, "Xera", "A factura en formato PDF", "Exporta o documento con nome en base á data e hora no directorio tmp/")



SHOW_FLOATING_LEGEND()

@enduml